---
# Docker configuration
docker_tz: Europe/Amsterdam
docker_network: homelab

# Mounting points
mounts:
  storage: "/mnt/bakkie-nasi"
  appdata: "/mnt/bakkie-bami"
  media: "/mnt/bakkie-nasi/Muziek"

# TrueNAS configuration
truenas:
  hostname: "truenas.{{ internal_hostname }}"
  webui_port: "81"

# AdGuard Home configuration
adguardhome:
  hostname: "adguard.{{ internal_hostname }}"
  datadir: "{{ mounts.appdata }}/adguardhome"
  dashboard_port: "10000"

# Traefik configuration
traefik:
  hostname: "traefik.{{ internal_hostname }}"
  datadir: "{{ mounts.appdata }}/traefik"

# Dozzle configuration
dozzle:
  hostname: "docker.{{ internal_hostname }}"
  datadir: "{{ mounts.appdata }}/dozzle"

# Jellyfin configuration
jellyfin:
  hostname: "jf.{{ external_hostname }}"
  datadir: "{{ mounts.appdata }}/jellyfin"
  mediadir: "{{ mounts.media }}"

# Sonarr configuration
sonarr:
  hostname: "sonarr.{{ internal_hostname }}"
  datadir: "{{ mounts.appdata }}/sonarr"
  mediadir: "{{ mounts.media }}"

# Radarr configuration
radarr:
  hostname: "radarr.{{ internal_hostname }}"
  datadir: "{{ mounts.appdata }}/radarr"
  mediadir: "{{ mounts.media }}"
