---
- name: "Running playbook"
  hosts: all
  serial: 1
  become: true

  vars_files:
    - vars/all/config.yaml
    - vars/all/vault.yaml

  roles:
    - geerlingguy.docker

  pre_tasks:
    - name: Check if user mode works.
      become: false
      ansible.builtin.debug:
        msg: "user mode ok"

    - name: Check if become mode works.
      become: true
      ansible.builtin.debug:
        msg: "become mode ok"

  handlers:
    - name: Include pre-stage handlers.
      ansible.builtin.import_tasks: tasks/handlers/pre.yml
    - name: Include run-stage handlers.
      ansible.builtin.import_tasks: tasks/handlers/run.yml

  tasks:
    - name: Configure Docker.
      ansible.builtin.import_tasks: tasks/setup/docker.yml
    - name: Configure Cloudflare DNS.
      ansible.builtin.import_tasks: tasks/setup/cloudflare.yml
    - name: Set up Traefik.
      ansible.builtin.import_tasks: tasks/traefik.yml
    - name: Set up Dozzle.
      ansible.builtin.import_tasks: tasks/dozzle.yml
    - name: Set up UpSnap.
      ansible.builtin.import_tasks: tasks/upsnap.yml
    - name: Set up Prowlarr.
      ansible.builtin.import_tasks: tasks/prowlarr.yml
    - name: Set up Jellyseerr.
      ansible.builtin.import_tasks: tasks/jellyseerr.yml
