---
- name: Create Dozzle data directories.
  ansible.builtin.file:
    path: "{{ dozzle.datadir }}"
    state: directory
    mode: "755"

- name: Transfer Dozzle template files.
  ansible.builtin.template:
    src: "templates/dozzle/compose.yaml.j2"
    dest: "{{ dozzle.datadir }}/compose.yaml"
    mode: "640"
  notify: Restart Dozzle

- name: Ensure Dozzle is running.
  community.docker.docker_compose_v2:
    project_src: "{{ dozzle.datadir }}"
    state: present
  register: dozzle_running
