---
# Traefik must ALWAYS be first! Otherwise services might not work.
- name: Restart Traefik
  become: true
  community.docker.docker_compose:
    project_src: "{{ traefik.datadir }}"
    state: present
    restarted: true
  when: not traefik_running.changed

# ----------------------------------------------------------------------

- name: Restart Dozzle
  become: true
  community.docker.docker_compose:
    project_src: "{{ dozzle.datadir }}"
    state: present
    restarted: true
  when: not dozzle_running.changed

- name: Restart UpSnap
  become: true
  community.docker.docker_compose:
    project_src: "{{ upsnap.datadir }}"
    state: present
    restarted: true
  when: not upsnap_running.changed

- name: Restart Jellyfin
  become: true
  community.docker.docker_compose:
    project_src: "{{ jellyfin.datadir }}"
    state: present
    restarted: true
  when: not jellyfin_running.changed

- name: Restart Jellyseerr
  become: true
  community.docker.docker_compose:
    project_src: "{{ jellyseerr.datadir }}"
    state: present
    restarted: true
  when: not jellyseerr_running.changed

- name: Restart Sonarr
  become: true
  community.docker.docker_compose:
    project_src: "{{ sonarr.datadir }}"
    state: present
    restarted: true
  when: not sonarr_running.changed

- name: Restart Radarr
  become: true
  community.docker.docker_compose:
    project_src: "{{ radarr.datadir }}"
    state: present
    restarted: true
  when: not radarr_running.changed

- name: Restart Recyclarr
  become: true
  community.docker.docker_compose:
    project_src: "{{ recyclarr.datadir }}"
    state: present
    restarted: true
  when: not recyclarr_running.changed

- name: Restart Prowlarr
  become: true
  community.docker.docker_compose:
    project_src: "{{ prowlarr.datadir }}"
    state: present
    restarted: true
  when: not prowlarr_running.changed

# ----------------------------------------------------------------------

# AdGuard Home must ALWAYS be last! Otherwise DNS will break during execution.
- name: Restart AdGuard Home
  become: true
  community.docker.docker_compose:
    project_src: "{{ adguardhome.datadir }}"
    state: present
    restarted: true
  when: not adguardhome_running.changed
