---
- name: Create Prowlarr data directories.
  ansible.builtin.file:
    path: "{{ prowlarr.datadir }}"
    state: directory
    mode: "755"

- name: Transfer Prowlarr template files.
  ansible.builtin.template:
    src: "templates/prowlarr/compose.yaml.j2"
    dest: "{{ prowlarr.datadir }}/compose.yaml"
    mode: "640"
  notify: Restart Prowlarr

- name: Ensure Prowlarr is running.
  community.docker.docker_compose_v2:
    project_src: "{{ prowlarr.datadir }}"
    state: present
  register: prowlarr_running
