---
- name: Create rdt-client data directories.
  become: true
  ansible.builtin.file:
    path: "{{ rdt.datadir }}/aria2" # ensures both datadir and datadir/aria2 exist
    state: directory
    mode: "755"

- name: Transfer rdt-client template files.
  become: true
  ansible.builtin.template:
    src: "templates/rdt/{{ item.src }}"
    dest: "{{ rdt.datadir }}/{{ item.dest }}"
    mode: "640"
  loop:
    - src: docker-compose.yml.j2
      dest: docker-compose.yml
    - src: aria2.conf.j2
      dest: aria2/aria2.conf
  notify: Restart rdt-client

- name: Ensure rdt-client is running.
  become: true
  community.docker.docker_compose:
    project_src: "{{ rdt.datadir }}"
    state: present
  register: rdt_running
