---
- name: Create Traefik data directories.
  ansible.builtin.file:
    path: "{{ traefik.datadir }}"
    state: directory
    mode: "755"

- name: Create Traefik ACME storage.
  ansible.builtin.file:
    path: "{{ traefik.datadir }}/acme.json"
    state: touch
    mode: "600"
    modification_time: preserve
    access_time: preserve

- name: Transfer Traefik template files.
  ansible.builtin.template:
    src: "templates/traefik/{{ item.src }}"
    dest: "{{ traefik.datadir }}/{{ item.dest }}"
    mode: "640"
  loop:
    - src: compose.yaml.j2
      dest: compose.yaml
    - src: traefik.yml.j2
      dest: traefik.yml
    - src: config.yml.j2
      dest: config.yml
  notify: Restart Traefik

- name: Ensure Traefik is running.
  community.docker.docker_compose_v2:
    project_src: "{{ traefik.datadir }}"
    state: present
  register: traefik_running
