---
- name: Create UpSnap data directories.
  ansible.builtin.file:
    path: "{{ upsnap.datadir }}"
    state: directory
    mode: "755"

- name: Transfer UpSnap template files.
  ansible.builtin.template:
    src: "templates/upsnap/compose.yaml.j2"
    dest: "{{ upsnap.datadir }}/compose.yaml"
    mode: "640"
  notify: Restart UpSnap

- name: Ensure UpSnap is running.
  community.docker.docker_compose_v2:
    project_src: "{{ upsnap.datadir }}"
    state: present
  register: upsnap_running
