---
- name: Create UpSnap data directories.
  become: true
  ansible.builtin.file:
    path: "{{ upsnap.datadir }}"
    state: directory
    mode: "755"

- name: Transfer UpSnap template files.
  become: true
  ansible.builtin.template:
    src: "templates/upsnap/docker-compose.yml.j2"
    dest: "{{ upsnap.datadir }}/docker-compose.yml"
    mode: "640"
  notify: Restart UpSnap

- name: Ensure UpSnap is running.
  become: true
  community.docker.docker_compose:
    project_src: "{{ upsnap.datadir }}"
    state: present
  register: upsnap_running
