---
- name: Restart Dozzle
  community.docker.docker_compose_v2:
    project_src: "{{ dozzle.datadir }}"
    state: restarted
  when: not dozzle_running.changed

- name: Restart UpSnap
  community.docker.docker_compose_v2:
    project_src: "{{ upsnap.datadir }}"
    state: restarted
  when: not upsnap_running.changed

- name: Restart Prowlarr
  community.docker.docker_compose_v2:
    project_src: "{{ prowlarr.datadir }}"
    state: restarted
  when: not prowlarr_running.changed
